/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MainCreateUserInfoResp } from './main-create-user-info-resp';
// May contain unused imports in some cases
// @ts-ignore
import type { MainResponse } from './main-response';

/**
 * @type CreateUserInfo200Response
 */
export type CreateUserInfo200Response = MainResponse;


